#! /bin/bash
#####################################################
### Specific configurations for the local machine ###
###     This file is sourced by the ~/.zshrc      ###
#####################################################

### Set env variables for the .zshrc
ZSH_CUSTOM=__CONFIG_HOME__/dotfiles/zsh/custom
ZSH_THEME="agnoster"

CSP_MANDIC_SCRIPTS_HOME=__CONFIG_HOME__/scripts

ANACONDA_HOME=$HOME/Miniconda/bin


#######################################
#########       ALIASES       #########
#######################################

### REMOTE CONTROL ###


### MOUNT DEVICES ###
