#! /bin/bash
#####################################################
### Specific configurations for the local machine ###
###     This file is sourced by the ~/.zshrc      ###
#####################################################

### Set env variables for the .zshrc
ZSH_CUSTOM=$HOME/.config/zsh
ZSH_THEME="agnoster"


### Set env variables related to CUDA
CUDA_HOME=/usr/local/cuda/bin
CUDA_LIB64_HOME=/usr/local/cuda/lib64
CUDA_CUPTI_LIB64_HOME=/usr/local/cuda/extras/CUPTI/lib64


### Set other env variables
ANACONDA_HOME=$HOME/Miniconda3/bin


### Export some custom environmental variables for user convenience.
export USER_LOG_DIR="/hdd/log/${USER}"
export USER_TMP_DIR="/hdd/tmp/${USER}"
export DATASETS_SSD="/home/datasets"
export DATASETS_HDD="/hdd/datasets"
export CSP_ICT_HOME="/hdd/csp-ict"
export EE_IK1614LX_SETUP_HOME="${CSP_ICT_HOME}/ee-ik1614lx/setup"
export EE_IK1614LX_UPDATE_HOME="${CSP_ICT_HOME}/ee-ik1614lx/update"
export EE_IK1614LX_DEFAULTS_HOME="${CSP_ICT_HOME}/ee-ik1614lx/defaults"
export JUPYTER_LAB_PORT=__JUPYTER_LAB_PORT__
export JUPYTER_NOTEBOOK_PORT=__JUPYTER_NOTEBOOK_PORT__
export TF_BOARD_PORT=__TF_BOARD_PORT__


#######################################
#########       ALIASES       #########
#######################################

### GENERAL ###


### PYTHON ###
alias jl='start_jupyter.sh'
alias jn='start_jupyter.sh --notebook'


### REMOTE CONTROL ###


### MOUNT DEVICES ###