#! /bin/bash
#####################################################
### Specific configurations for the local machine ###
###     This file is sourced by the ~/.zshrc      ###
#####################################################

### Set env variables for the .zshrc
ZSH_CUSTOM=$HOME/.config/zsh
ZSH_THEME="agnoster"

### Set other env variables
ANACONDA_HOME=$HOME/Miniconda3/bin


#######################################
#########       ALIASES       #########
#######################################

### REMOTE CONTROL ###


### MOUNT DEVICES ###
