#!/usr/bin/env bash

set -e

function help() {

local _FILE_NAME
_FILE_NAME=`basename ${BASH_SOURCE[0]}`

cat << HELP_USAGE

Description:
    Generate inplace TOC for Markdown files. Based on 'gh-md-toc'

Usage: $_FILE_NAME [-h|--help] [-a=|--author=<AUTHOR>] [-r|--remove-bak]
    [-f=|--file=<FILE_NAME>] [-s=|--sys-prefix=<PATH>]

Examples:
    $_FILE_NAME --remove-bak
    $_FILE_NAME --author="My Name"
    $_FILE_NAME --file="My_readme_file.md"
    $_FILE_NAME --file="My_readme_file.md" --sys-prefix="/path/to/dir/with/my_readme_file"

Options:
    -h|--help
        Show this message.

    -a=|--author=<AUTHOR>
        Defines author of so-generated TOC table.
        Defaults to value of 'whoami'.

    -f=|--file=<FILE_NAME>
        Defines the name of file for which TOC table will be generated.
        Must have markdown file extension ('*.md')
        Default is 'README.md'

    -s=|--sys-prefix=<PATH>
        Defines path the file for which TOC table will be generated.
        Defaults to the location of where is script is executed.

    -r|--remove-bak
        Removes backup files that are generated by 'gh-md-toc'.
        By default these files are saved in .gh-md-toc.bak in
        current directory (auto created if it does not exist).

Author:
    Ilya Kisil <ilyakisil@gmail.com>

Report bugs to ilyakisil@gmail.com.

HELP_USAGE
}

### Default value for variables
sys_prefix=`pwd`
md_file_name="README.md"
author=`whoami`
keep_backup_files=1

### Parse arguments
for arg in "$@"; do
    case $arg in
        -h|--help)
            help
            exit
            ;;
        -a=*|--author=*)
            author="${arg#*=}"
            ;;
        -r|--remove-bak)
            keep_backup_files=0
            ;;
        -f=*|--file=*)
            md_file_name="${arg#*=}"
            ;;
        -s=*|--sys-prefix=*)
            sys_prefix="${arg#*=}"
            ;;
        *)
            # Skip unknown option
            ;;
    esac
    shift
done

### Define new variables with respect to the parsed arguments
backup_dir=${sys_prefix}/.gh-md-toc.bak
md_file=${sys_prefix}/${md_file_name}
md_file_orig=${md_file_name}.orig.*
md_file_toc=${md_file_name}.toc.*


### Main
#if [ ! ${md_file: -3} == ".md" ]; then
if [[ ${md_file} != *.md ]]; then
    echo "ERROR: This script can only be used for files with Markdown extension (*.md)" >&2
    echo "$md_file" >&2
    exit
fi

if [ ! -f ${md_file} ]; then
    echo "ERROR: Specified file does not exist." >&2
    echo "$md_file" >&2
    exit
fi


### Generate and append TOC
bash  gh-md-toc --insert $md_file;


### Move or delete auto generated files (Matched using wildcard)
if [ $keep_backup_files -eq 1 ]; then
    if [ ! -d $backup_dir ]; then
        mkdir $backup_dir
    fi
    # Change directory and don't rename
    mv ${sys_prefix}/$md_file_orig $backup_dir/
    mv ${sys_prefix}/$md_file_toc $backup_dir/
else
    rm ${sys_prefix}/$md_file_orig
    rm ${sys_prefix}/$md_file_toc
fi


### Change name of who added TOC. When it is generated by 'gh-md-toc' this is defined by `whoami`.
# Use default prefix in order to ensure it will be changed in the correct place and only the first match.
author_prefix="<!-- Added by:"
author_default=`whoami`

# Skip if author name has not been provided
if [[ $author != $author_default ]]; then
    # !!" DO NOT REMOVE white spaces in sed !!!
    sed -i "1,/$author_prefix $author_default/ s/$author_prefix $author_default/$author_prefix $author/" $md_file
fi
